table Customer
	lineageTag: 62edfb0f-0b59-48a5-a597-b378da11c095

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b59a8f6d-14f1-4032-b0e1-a8884153bc83
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2fcd0fc0-ecb0-47d1-b193-161d7947072a
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: f0a658a2-77a3-480a-8821-041da83ee8d7
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 3ba3e84b-a945-48db-b50c-f8eca94498a3
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: b4a14fa4-b75b-48f8-a309-61cb8098e2a1
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 8f7b4039-6224-49fe-8f35-6fad1bea110d
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: f5ffff1c-a394-4a8c-b6b7-b67f17b2de4a
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	hierarchy Geography
		lineageTag: 4642398b-7649-4352-a028-8607a58aa576

		level Country-Region
			lineageTag: 060936a1-0500-4846-a1c8-7c514767e9eb
			column: Country-Region

		level State-Province
			lineageTag: 12c61d8d-0349-41ac-af9f-c433724fe9d8
			column: State-Province

		level City
			lineageTag: c458fae4-1d3f-45ed-8f97-26ff02445912
			column: City

		level 'Postal Code'
			lineageTag: ac066dfd-559c-4a85-aa49-ab4ed0123850
			column: 'Postal Code'

		level Customer
			lineageTag: 1336461b-8d77-4cdd-a374-e14851c72b3e
			column: Customer

	partition Customer-01f41322-c19c-4b65-a4cb-85a8045da233 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_DimCustomer = Source{[Schema="dbo",Item="DimCustomer"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimCustomer,{"CustomerKey", "CustomerAlternateKey", "FirstName", "LastName", "DimGeography"}),
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimGeography", {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}, {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}),
				    #"Merged Columns" = Table.CombineColumns(#"Expanded DimGeography",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Customer"),
				    #"Add NA Row" = Table.InsertRows(#"Merged Columns", 0, {[CustomerKey = -1, CustomerAlternateKey = "[Not Applicable]", Customer = "[Not Applicable]", City = "[Not Applicable]", StateProvinceName ="[Not Applicable]", EnglishCountryRegionName ="[Not Applicable]", PostalCode ="[Not Applicable]"]}),
				    #"Renamed Columns" = Table.RenameColumns(#"Add NA Row",{{"CustomerAlternateKey", "Customer ID"}, {"StateProvinceName", "State-Province"}, {"EnglishCountryRegionName", "Country-Region"}, {"PostalCode", "Postal Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

