table Product
	lineageTag: 73872a46-d921-4207-9264-3a7387ff4c2a

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1464a08b-d9d3-411c-a9ce-439b832ec215
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: f0acd1a9-4061-49e6-8a6b-eb07dfbcd8a7
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Standard Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2e7e2c1f-743d-4372-90a8-b690d72570ba
		summarizeBy: none
		sourceColumn: Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Color
		dataType: string
		lineageTag: 6f34f6f0-39e1-4fc6-929c-1c4f68810762
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'List Price'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: be2441bf-619a-498b-ab8d-2158af7dec53
		summarizeBy: none
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Model
		dataType: string
		lineageTag: 652c6746-6a12-4767-b7eb-cede0dff7262
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 111c94c8-43b3-4583-b91a-2be3ed7fe6f8
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5fabd730-54ca-4ebf-93d2-1620ee96dcfa
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	/// Stock-keeping unit
	column SKU
		dataType: string
		lineageTag: 8998f00a-9694-4188-bd45-a422dba3ef20
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	hierarchy Products
		lineageTag: 0776eb0f-7cfb-4f5f-ba97-d6560c574217

		level Category
			lineageTag: 4d5ab193-5a6e-4042-8b11-aeabf8037e70
			column: Category

		level Subcategory
			lineageTag: c850924f-634e-4f51-95d5-429c651e81fd
			column: Subcategory

		level Model
			lineageTag: 1185bbc0-5095-49c3-9339-e1f97e66b6df
			column: Model

		level Product
			lineageTag: 36cb02f3-fa1b-4d92-9e16-099750cf0b21
			column: Product

	partition Product-3d5e98b2-a997-4444-96bb-fe1718e2f2b8 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_DimProduct, each ([FinishedGoodsFlag] = true)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"ProductKey", "ProductAlternateKey", "EnglishProductName", "StandardCost", "Color", "ListPrice", "ModelName", "DimProductSubcategory"}),
				    #"Expanded DimProductSubcategory" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimProductSubcategory", {"EnglishProductSubcategoryName", "DimProductCategory"}, {"EnglishProductSubcategoryName", "DimProductCategory"}),
				    #"Expanded DimProductCategory" = Table.ExpandRecordColumn(#"Expanded DimProductSubcategory", "DimProductCategory", {"EnglishProductCategoryName"}, {"EnglishProductCategoryName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded DimProductCategory",{{"EnglishProductName", "Product"}, {"StandardCost", "Standard Cost"}, {"ListPrice", "List Price"}, {"ModelName", "Model"}, {"EnglishProductSubcategoryName", "Subcategory"}, {"EnglishProductCategoryName", "Category"}, {"ProductAlternateKey", "SKU"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

