table Sales
	lineageTag: f0d5eb7d-43c9-450c-9660-fe59a6811757

	measure Revenue = SUM(Sales[Sales Amount])
		formatString: "₹"\ #,0.00;#,0.00\ -"₹";"₹"\ #,0.00
		lineageTag: f3e4347b-9d49-4985-a841-d154ea1e416a

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure Cost = SUM(Sales[Product Standard Cost])
		formatString: "₹"\ #,0.00;#,0.00\ -"₹";"₹"\ #,0.00
		lineageTag: 801f1ffe-00d9-4acf-8c5f-492d3f54d8fc

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure Profit = [Revenue] - [Cost]
		formatString: "₹"\ #,0.00;#,0.00\ -"₹";"₹"\ #,0.00
		lineageTag: f59dee16-650a-4fd6-bd65-8251b489ddb7

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure Quantity = SUM(Sales[Order Quantity])
		formatString: #,0
		lineageTag: cb98788f-6fd3-43fd-ac3b-65a714f7f7c4

	measure 'Minimum Price' = MIN(Sales[Unit Price])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 9235ad5c-68b9-4f69-ab76-65b492f986ef

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Maximum Price' = SUM(Sales[Unit Price])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 3f6de17e-93c4-4a46-8a4d-6917dc6bd260

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Average Price' = AVERAGE(Sales[Unit Price])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: f1afd146-3a89-4fa7-9f48-b558a7fe849a

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Order Line Count' = COUNTROWS(Sales)
		formatString: 0
		lineageTag: 9d1b2b0a-973f-4963-99c2-0b9c448b95f2

	measure 'Order Count' = DISTINCTCOUNT('Sales Order'[Sales Order])
		formatString: 0
		lineageTag: 6e2932fd-7e87-475c-9c58-5bcfbd879a4d

	measure 'Profit Margin' = DIVIDE([Profit], [Revenue])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 17715442-5013-4e2b-b79d-b45460f9c8b7

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e24dd6ce-9024-4124-b946-1ba4be27cc8d
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 61c23733-ee12-47b5-8279-b8697d5cbe80
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d1bfcfc4-d674-4404-9871-edba90a58112
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b26bfed6-3fa1-4f39-9888-dff838754a78
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 39851a83-3d88-475f-92a7-6d192fd2d707
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: abb31b1d-2862-42b0-9544-5faea7a2942c
		summarizeBy: count
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0468f148-119d-4e54-9f6e-40b828c6b795
		summarizeBy: count
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5631db8a-b31c-44b9-9acc-8b7efb387237
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: #,0
		lineageTag: 46de3f69-8c82-4d73-88bf-b11240ff0e22
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: cab61f73-397a-4468-bac7-156ad1e81b9b
		summarizeBy: average
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Extended Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 74cc9c10-6444-491c-be2b-33c68575e2ca
		summarizeBy: sum
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Product Standard Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f56293fe-ee0c-44c0-9444-6ecbedad78a5
		summarizeBy: sum
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Total Product Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 200212c2-cdbf-4ef4-831c-f7c5d52fa83d
		summarizeBy: sum
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 171ea2d6-e500-4376-b4b4-a78b613a78cb
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Price Discount Pct'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7d683530-3b88-44bf-abfa-8212a827cd56
		summarizeBy: none
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = User

	partition Sales-1c496a38-f0f4-4d25-b987-657177c38553 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"SalesOrderLineKey", "ResellerKey", "CustomerKey", "ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "ExtendedAmount", "UnitPriceDiscountPct", "ProductStandardCost", "TotalProductCost", "SalesAmount"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"OrderQuantity", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ExtendedAmount", "Extended Amount"}, {"OrderQuantity", "Order Quantity"}, {"ProductStandardCost", "Product Standard Cost"}, {"SalesAmount", "Sales Amount"}, {"TotalProductCost", "Total Product Cost"}, {"UnitPrice", "Unit Price"}, {"UnitPriceDiscountPct", "Unit Price Discount Pct"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

