table 'Sales Order'
	lineageTag: c121d967-6a60-4b48-9532-a3b3cc29659b

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 48c88091-adb2-4faa-9463-6f145461dfb4
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: c05c6169-dd4b-430f-af23-80648d568972
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: 8b2864bb-93a5-4006-bf8e-bd4cc16e74fe
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Sales Order Line
		sortByColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: ad990a89-c378-473c-ae7e-31a4898f50d5
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sales Orders'
		lineageTag: eca17744-d4da-43a0-963f-7c25c395b463

		level 'Sales Order'
			lineageTag: 1d1d586a-281a-4091-b7f0-79922377708b
			column: 'Sales Order'

		level 'Sales Order Line'
			lineageTag: d68e91d6-65b7-4285-8711-a760cc771cb9
			column: 'Sales Order Line'

	partition 'Sales Order-3ce1b467-3e1b-4732-b605-3e94fee75991' = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"Channel", "SalesOrderLineKey", "SalesOrderNumber", "SalesOrderLineNumber"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"SalesOrderNumber", "Sales Order"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Sales Order Line", each [Sales Order] & " - " & Text.PadStart(Number.ToText([SalesOrderLineNumber]), 2, "0")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Sales Order Line", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SalesOrderLineNumber"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

